# action.yml
name: 'AWS Elastic Beanstalk Cli for setting environment variables'

author: Simon Ouyang

description: 'AWS Elastic Beanstalk Cli for setting environment variable'

branding:
  icon: 'terminal'  
  color: 'white'
  
inputs:
  command:  #
    description: '<command>'
    required: true
    default: 'eb --version'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.command }}
