# action.yml
name: 'AWS Elastic Beanstalk cli for multiple commands'

author: Simon Ouyang

description: 'Provide eb cli commands that support multiple commands'

branding:
  icon: 'terminal'  
  color: 'white'
  
inputs:
  command:  # input example: eb use test && eb setenv foo=bar
    description: '<command>'
    required: true
    default: 'eb --version'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.command }}
