# action.yml
name: 'AWS Elastic Beanstalk Cli for setting environment variables'

author: Simon Ouyang

description: 'AWS Elastic Beanstalk Cli for setting environment variable'

branding:
  icon: 'terminal'  
  color: 'white'
  
inputs:
  application_environment:  #
    description: '<application_environment>'
    required: true
    default: 'my_environment'
  environment_variable:  # input example: foo=bar
    description: '<environment_variable>'
    required: true
    default: 'foo=bar' 

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.application_environment }}
    - ${{ inputs.environment_variable }}
